Patient/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('interface.urls', namespace='interface')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('info.urls', namespace='info')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info/urls.py
from django.urls import path, re_path
from .import views
from rest_framework.routers import DefaultRouter


app_name = 'info'


router = DefaultRouter()
router.register('patient/info', views.PatientInfoViewSet)
router.register('patient/ecg', views.ECGInformationViewSet)
router.register('doctors', views.DoctorUsersViewset)


urlpatterns = [
    path('post-user', views.create_user),
    path('token', views.CustomAuthToken.as_view()),
]


urlpatterns += router.urls

interface/urls.py
from django.urls import path

from . import views

app_name = 'interface'

urlpatterns = [
    path('', views.home, name='home'),
    path('history/considerd_ones/', views.ecgs_considered, name='considerd_ecgs'),
    path('info/<int:pk>/<slug:slug>/', views.patient_info, name='patient_info'),
    path('ecg/<int:pk>/<slug:slug>/', views.patient_ecg, name='patient_ecg'),
    path('nurse/<int:pk>/', views.nurse_history, name='nurse_history'),
    path('patient/<int:pk>/', views.patient_history, name='patient_history'),
    path('considerations/<int:pk>/', views.write_consideration, name='set_considerations'),
    path('update_consideration/<int:pk>/', views.update_consideration, name='update_consideration'),
]

interface/models.py
from django.db import models

# Create your models here.

interface/forms.py
from django import forms



class DoctorConsiderationForm(forms.Form) :
    considerations = forms.CharField(label='Considerations', help_text='Required',
                                    widget=forms.Textarea(attrs={'rows': 15}))

    def clean_considerations(self) :
        considerations = self.cleaned_data['considerations']
        if considerations == '' :
            return forms.ValidationError('Consideration can not be empty')
        return considerations

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['considerations'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Considerations'})

interface/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.files.storage import default_storage
from django.conf import settings
from customUser.models import User

import json

from info.models import ECGInformation, Information, DoctorConsideration

from .decorators import info_permission, ecg_permission, is_doctor

from .forms import DoctorConsiderationForm

def prepare_for_plot(ecg) :
    channels = []
    for i in range(12) :
        channels.append([])

    for signal in ecg :
        for j in range(len(channels)) :
            channels[j].append(signal[f'ch{j+1}'])

    data = {}
    for i in range(12) :
        data[f'ch{i+1}'] = channels[i]
    
    return data


@login_required
def home(request) :
    all_ecgs = ECGInformation.objects.filter(doctors__in=[request.user, ]).order_by('-created')

    not_considered_ecgs = []
    for item in all_ecgs :
        if not item.considerations.filter(doctor=request.user) :
            not_considered_ecgs.append(item)
    paginator = Paginator(not_considered_ecgs, 10)

    # paginator = Paginator(all_ecgs, 5)
    page_number = request.GET.get('page')
    ecgs = paginator.get_page(page_number)
    return render(request, 'interface/home.html', {'ecgs' : ecgs, 'doctor_pk' : request.user.pk})


@login_required
@info_permission
def patient_info(request, pk, slug) :
    info = get_object_or_404(Information, pk=pk, slug=slug)
    return render(request, 'interface/patient_information.html', {'info' : info})


@login_required
@ecg_permission
def patient_ecg(request, pk, slug) :
    ecg = get_object_or_404(ECGInformation, pk=pk, slug=slug)
    info = get_object_or_404(Information, pk=ecg.patient.pk)
    path = ecg.ecg.url.strip(settings.MEDIA_URL)
    ecg_file = json.load(default_storage.open(path))
    data = prepare_for_plot(ecg_file)
    name = ecg.patient.fullname

    return render(request, 'interface/patient_ecg.html', {'data': data, 'info': info, 'name': name})


@login_required
@is_doctor
def nurse_history(request, pk) :
    nurse = get_object_or_404(User, pk=pk).fullname
    all_ecgs= ECGInformation.objects.filter(nurse_id=pk).order_by('-created')
    paginator = Paginator(all_ecgs, 10)
    page_number = request.GET.get('page')
    ecgs = paginator.get_page(page_number)
    return render(request, 'interface/nurse_history.html', {'ecgs' : ecgs, 'owner' : nurse})

@login_required
@is_doctor
def patient_history(request, pk) :
    patient = get_object_or_404(Information, pk=pk).fullname
    all_ecgs= ECGInformation.objects.filter(patient_id=pk).order_by('-created')
    paginator = Paginator(all_ecgs, 10)
    page_number = request.GET.get('page')
    ecgs = paginator.get_page(page_number)
    return render(request, 'interface/patient_history.html', {'ecgs' : ecgs, 'owner' : patient})


# needs decorators for permission
def write_consideration(request, pk) :
    if request.method == 'POST' :
        form = DoctorConsiderationForm(request.POST)
        if form.is_valid() :
            considerations = request.POST.get('considerations')
            ecg = get_object_or_404(ECGInformation, pk=pk)
            a = DoctorConsideration.objects.create(doctor=request.user, ecg=ecg,
                                    doctor_considerations=considerations, is_considered=True)

            return redirect('interface:home')

    form = DoctorConsiderationForm()
    return render(request, 'interface/consideration_form.html', {'form':form})


# * VIEWS IN THIS PART ARE RELATED TO THE CONSIDERED ECGs

@login_required
def ecgs_considered(request) :
    all_ecgs = ECGInformation.objects.filter(doctors__in=[request.user, ]).order_by('-created')

    considered_ecgs = []
    for item in all_ecgs :
        if item.considerations.filter(doctor=request.user) :
            considered_ecgs.append(item)


    consideration_ids = [] 
    for item in considered_ecgs :
        print(item)
        consideration_ids.append(item.considerations.get(ecg=item).pk)
    
    
    # paginator = Paginator(all_ecgs, 5)
    paginator_ecgs = Paginator(considered_ecgs, 10)
    paginator_links = Paginator(consideration_ids, 10)
    page_number = request.GET.get('page')
    ecgs = paginator_ecgs.get_page(page_number)
    links_ids = paginator_links.get_page(page_number)

    data = zip(ecgs, links_ids)
    context = {'data' : data, 'doctor_pk' : request.user.pk}

    return render(request, 'interface/considered_ecgs.html', context=context)


# needs decorators for permission
# probably a slug is needed
def update_consideration(request, pk) :
    if request.method == 'POST' :
        form = DoctorConsiderationForm(request.POST)
        if form.is_valid() :
            considerations = request.POST.get('considerations')
            DoctorConsideration.objects.filter(pk=pk).update(doctor_considerations=considerations)

            return redirect('interface:considerd_ecgs')

    data = {'considerations' : DoctorConsideration.objects.get(pk=pk).doctor_considerations}
    form = DoctorConsiderationForm(initial=data)
    return render(request, 'interface/consideration_form.html', {'form':form})

templates/interface/consideration_form.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Consideration{% endblock %}


{% block content %}
{% include 'base/nav-main.html' %}
<div class="container" style="width: 65%; outline: none; background: transparent;">
    <div class="row">
        <div class="col-12">
            <div class="card text-center card-form" style="border: none; background: transparent;">
                <div class="card-body">
                    {% include 'registration/messages.html' %}
                    <h3 style="color: var(--clr-grey-2); margin-bottom: 3rem;">Set your considerations for the patient please</h3>

                    {% if form.errors %}
                        <p>Please correct the following errors:</p>
                            {% for field in form %}
                                {% if field.errors %}
                                <div class="alert alert-primary" role="alert">
                                    {{ field.errors|striptags }}
                                </div>
                                {% endif %}
                            {% endfor %}
                    {% endif %}


                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="small font-weight-bold">{{ form.considerations.label }}
                            </label>
                            {{ form.considerations }}
                        </div>

                        <br>
                        <input type="submit" value="Submit" class="btn btn-block mx-auto" style="width: 28%; background: rgba(38, 82, 102, 0.59);">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/interface/considered_ecgs.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/interface/home.css' %}">
{% endblock %}


{% block title %}Home{% endblock %}


{% block content %}
{% include 'base/nav-main.html' %}

<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Patient</th>
                <th scope="col">Nurse</th>
                <th scope="col">ECG at</th>
                <th scope="col">ECG</th>
                <th scope="col">Patient information</th>
                <th scope="col">Considerations</th>
            </tr>
        </thead>
        <tbody>
            {% for ecg, link_id in data %}
            <tr>
                <th><a href="{% url 'interface:patient_history' ecg.patient.pk %}">{{ ecg.patient.fullname }}</a></th>
                <th><a href="{% url 'interface:nurse_history' ecg.nurse.pk %}">{{ ecg.nurse.fullname }}</a></th>
                <th>{{ ecg.recorded_at|naturaltime }}</th>
                <th><a class="patient-link" href="{{ ecg.get_absolute_url }}"><i class="fas fa-link"></i></a></th>
                <th><a class="patient-link" href="{{ ecg.patient.get_absolute_url }}"><i class="fas fa-link"></i></a></th>
                <th>
                    <a class="patient-link" href="{% url 'interface:update_consideration' link_id %}">
                        <i class="fas fa-external-link-alt"></i>
                    </a>
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

templates/interface/home.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/interface/home.css' %}">
{% endblock %}


{% block title %}Home{% endblock %}


{% block content %}
{% include 'base/nav-main.html' %}

<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Patient</th>
                <th scope="col">Nurse</th>
                <th scope="col">Latest ECG at</th>
                <th scope="col">Latest ECG</th>
                <th scope="col">Patient information</th>
                <th scope="col">Set consideration</th>
            </tr>
        </thead>
        <tbody>
            {% for ecg in ecgs %}
            <tr>
                <th><a href="{% url 'interface:patient_history' ecg.patient.pk %}">{{ ecg.patient.fullname }}</a></th>
                <th><a href="{% url 'interface:nurse_history' ecg.nurse.pk %}">{{ ecg.nurse.fullname }}</a></th>
                <th>{{ ecg.recorded_at|naturaltime }}</th>
                <th><a class="patient-link" href="{{ ecg.get_absolute_url }}"><i class="fas fa-link"></i></a></th>
                <th><a class="patient-link" href="{{ ecg.patient.get_absolute_url }}"><i class="fas fa-link"></i></a></th>
                <th>
                    <a class="patient-link" href="{% url 'interface:set_considerations' ecg.pk %}">
                        <i class="fas fa-external-link-alt"></i>
                    </a>
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

templates/interface/nurse_history.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/interface/home.css' %}">
{% endblock %}


{% block title %}{{ nurse|title }}{% endblock %}


{% block content %}
{% include 'base/nav-main.html' %}

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Patient</th>
                <th scope="col">Doctors</th>
                <th scope="col">ECG at</th>
                <th scope="col">ECG</th>
                <th scope="col">Patient information</th>
            </tr>
        </thead>
        <tbody>
            {% for ecg in ecgs %}
            <tr>
                <th>{{ ecg.patient.fullname }}</th>
                {% with ecg.doctors.all as doctors %}
                <th>
                <select>
                    {% for doctor in doctors %}
                        <option>{{ doctor.fullname }}</option>
                    {% endfor %}
                </select>
                </th>
                {% endwith %}
                <th>{{ ecg.recorded_at|naturaltime }}</th>
                <th><a class="patient-link" href="{{ ecg.get_absolute_url }}"><i class="fas fa-link"></i></a></th>
                <th><a class="patient-link" href="{{ ecg.patient.get_absolute_url }}"><i class="fas fa-link"></i></a></th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

templates/interface/patient_ecg.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}
{% load verbose_names %}

{% block title %}{{ name|title }} ECG{% endblock %}


{% block content %}
{% include 'base/nav-main.html' %}

<style>
.channel {
    height: 300px;
    width: 100%;
}
</style>


<div class="container" style="width: 100%; max-width: 1350px;">
    <div class="row">

        <div class="col-3">
            <div class="container">
                <table class="table table-hover" id="patient-information">
                    {% for field, val in info %}
                    <tr>
                        <th style="font-size: 0.65rem;">{{ field }}</th>
                        <td style="font-size: 0.65rem;">{{ val }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th>{{ info|reveal:"created" }}</th>
                        <td>{{ info.created|naturaltime }}</td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="col-9">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="col channel" id="ch1"></div>
                        <div class="col channel" id="ch2"></div>
                        <div class="col channel" id="ch3"></div>
                        <div class="col channel" id="ch4"></div>
                    </div>
                    <div class="col">
                        <div class="col channel" id="ch5"></div>
                        <div class="col channel" id="ch6"></div>
                        <div class="col channel" id="ch7"></div>
                        <div class="col channel" id="ch8"></div>
                    </div>
                    <div class="col">
                        <div class="col channel" id="ch9"></div>
                        <div class="col channel" id="ch10"></div>
                        <div class="col channel" id="ch11"></div>
                        <div class="col channel" id="ch12"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js-files %}
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<script>
    const information = document.getElementById('patient-information');
    const infoHeight = information.offsetHeight;
</script>


<script>
    const ecg = {{data|safe}};
    for (var k in ecg) {
        if (ecg.hasOwnProperty(k)) {
            showChannel(k, ecg[k])
        }
    }
    function showChannel(chann_name, ecg_chann_data) {
    
    var limit = ecg_chann_data.length;
    var data = [];
    var dataSeries = { type: "line" };
    var dataPoints = [];
    for (var i = 0; i < limit; i += 1) {
        dataPoints.push({
            x: i,
            y: ecg_chann_data[i]
        });
    }
    dataSeries.dataPoints = dataPoints;
    data.push(dataSeries);
    
    //Better to construct options first and then pass it as a parameter
    var options = {
        zoomEnabled: true,
        animationEnabled: true,
        title: {
            text: `${chann_name}`
        },
        axisY: {
            lineThickness: 1
        },
        data: data  // random data
    };
    
    var chart = new CanvasJS.Chart(`${chann_name}`, options);
    document.getElementById(`${chann_name}`).style.height = `${infoHeight/12}px`;
    chart.render();
    
    }
</script>





{% endblock %}

templates/interface/patient_history.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/interface/home.css' %}">
{% endblock %}


{% block title %}{{ owner|title }}{% endblock %}


{% block content %}
{% include 'base/nav-main.html' %}

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nurse</th>
                <th scope="col">Doctors</th>
                <th scope="col">ECG at</th>
                <th scope="col">ECG</th>
                <th scope="col">Patient information</th>
            </tr>
        </thead>
        <tbody>
            {% for ecg in ecgs %}
            <tr>
                <th>{{ ecg.nurse.fullname }}</th>
                {% with ecg.doctors.all as doctors %}
                <th>
                <select>
                    {% for doctor in doctors %}
                        <option>{{ doctor.fullname }}</option>
                    {% endfor %}
                </select>
                </th>
                {% endwith %}
                <th>{{ ecg.recorded_at|naturaltime }}</th>
                <th><a class="patient-link" href="{{ ecg.get_absolute_url }}"><i class="fas fa-link"></i></a></th>
                <th><a class="patient-link" href="{{ ecg.patient.get_absolute_url }}"><i class="fas fa-link"></i></a></th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

templates/interface/patient_information.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}
{% load verbose_names %}
{% block title %}{{ info.fullname|title }} Info{% endblock %}


{% block content %}
{% include 'base/nav-main.html' %}

<div class="container">
    <table class="table table-hover">
        {% for field, val in info %}
        <tr>
            <th>{{ field }}</th>
            <td>{{ val }}</td>
        </tr>
        {% endfor %}
        <tr>
            <th>{{ info|reveal:"created" }}</th>
            <td>{{ info.created|naturaltime }}</td>
        </tr>
    </table>
</div>


{% endblock %}