Patient/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('interface.urls', namespace='interface')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('info.urls', namespace='info')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

info/urls.py
from django.urls import path, re_path
from .import views
from rest_framework.routers import DefaultRouter


app_name = 'info'


router = DefaultRouter()
router.register('patient/info', views.PatientInfoViewSet)
router.register('patient/ecg', views.ECGInformationViewSet)
router.register('doctors', views.DoctorUsersViewset)


urlpatterns = [
    path('post-user', views.create_user),
    path('token', views.CustomAuthToken.as_view()),
]


urlpatterns += router.urls

interface/urls.py
from django.urls import path

from . import views

app_name = 'interface'

urlpatterns = [
    path('', views.home, name='home'),
    path('history/considerd_ones/', views.ecgs_considered, name='considerd_ecgs'),
    path('info/<int:pk>/<slug:slug>/', views.patient_info, name='patient_info'),
    path('ecg/<int:pk>/<slug:slug>/', views.patient_ecg, name='patient_ecg'),
    path('nurse/<int:pk>/', views.nurse_history, name='nurse_history'),
    path('patient/<int:pk>/', views.patient_history, name='patient_history'),
    path('considerations/<int:pk>/', views.write_consideration, name='set_considerations'),
    path('update_consideration/<int:pk>/', views.update_consideration, name='update_consideration'),
]

templates/base/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/base/navbar1.css' %}">


    <style>
    </style>
    {% block links %}
    {% endblock %}
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    {% block js-files %}
    {% endblock %}

</body>
</html>

templates/base/nav-main.html
<style>
    a {
        color: var(--clr-grey-2);
    }
    a:hover {
        transition: var(--transition);
        text-decoration: none;
        cursor: pointer;
        color: var(--clr-white);
    }
</style>


<div id="main-navbar" class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="/">ECG-INFO Application</a>
    </h5>
    <nav class="my-2 my-md-0 mr-md-3 ml-auto">
        {% if request.user.is_authenticated %}
            <a class="p-2" href="{% url 'interface:home' %}">Home</a>
        {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
    <ul class="navbar-nav">
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                History
            </a>
            
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{% url 'interface:considerd_ecgs' %}">Considered ECGs</a>
                <div class="dropdown-divider"></div>
            </div>
        </li>
    </ul>
    <ul class="navbar-nav ml-3">
        <li class="nav-item dropdown">
            
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                {{ request.user.fullname }}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="#" class="dropdown-item">Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
    {% else %}
    <nav>
        <a class="p-2" href="{% url 'accounts:login' %}">Login</a>
    </nav>
    {% endif %}
</div>